[workspace]

members = [
    #    "pw_gix",
    #    "pw_gix_derive",
    "pw_gtk_ext",
    "pw_gtk_ext_derive",
    "component_test_gui",
    "gtk_ext_test_gui",
    "gtk3_ext",
    "gtk3_ext_derive",
    "gtk3_ext_test_gui",
]

resolver = "3"

[workspace.dependencies]
path_utilities = { git = "https://github.com/pwil3058/rust_utilities" }
#path_utilities = { path = "../rust_utilities/path_utilities" }
recollections = { git = "https://github.com/pwil3058/rust_utilities" }
#recollections = { path = "../rust_utilities/recollections" }
