[package]
name = "pw_gix"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]

[dependencies]
cairo-rs = "0.2.0"
gdk = "0.6.0"
gio = "0.2.0"
glib = "0.3.1"
gtk = "0.2.0"

fs2 = "0.4.2"
num = "0.1.40"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
