[workspace]

members = [
    "pw_gix",
    "pw_gix_derive",
    "pw_gtk_ext",
    "pw_gtk_ext_derive",
    "component_test_gui",
    "gtk_ext_test_gui",
    "recollections",
    "path_utilities",
    #    "orbtk_test_gui",
]
